// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7M_TuLRIIW8L__Clv7XR64X-RJiwSqs0',
    appId: '1:439024699088:web:6e123fcfc891e468af80d5',
    messagingSenderId: '439024699088',
    projectId: 'whatsapp-70290',
    authDomain: 'whatsapp-70290.firebaseapp.com',
    storageBucket: 'whatsapp-70290.firebasestorage.app',
    measurementId: 'G-D721M72QQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvo31oXrNWTV9ZoRtpEHCIyumMe-qUASA',
    appId: '1:439024699088:android:72bb07170a0e0b0caf80d5',
    messagingSenderId: '439024699088',
    projectId: 'whatsapp-70290',
    storageBucket: 'whatsapp-70290.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDABHgiPA9y9nfdAyUssxojU76RXX4eFGA',
    appId: '1:439024699088:ios:e12bedbed2843d1baf80d5',
    messagingSenderId: '439024699088',
    projectId: 'whatsapp-70290',
    storageBucket: 'whatsapp-70290.firebasestorage.app',
    iosBundleId: 'com.example.whatsappMessengerNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDABHgiPA9y9nfdAyUssxojU76RXX4eFGA',
    appId: '1:439024699088:ios:e12bedbed2843d1baf80d5',
    messagingSenderId: '439024699088',
    projectId: 'whatsapp-70290',
    storageBucket: 'whatsapp-70290.firebasestorage.app',
    iosBundleId: 'com.example.whatsappMessengerNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7M_TuLRIIW8L__Clv7XR64X-RJiwSqs0',
    appId: '1:439024699088:web:3117855e47cd366caf80d5',
    messagingSenderId: '439024699088',
    projectId: 'whatsapp-70290',
    authDomain: 'whatsapp-70290.firebaseapp.com',
    storageBucket: 'whatsapp-70290.firebasestorage.app',
    measurementId: 'G-YR819SG8EP',
  );

}